targets:
  $default:
    builders:
      # Freezed: ONLY in entities
      freezed|freezed:
        generate_for:
          include:
            - lib/**/entities/**.dart
          exclude:
            - lib/**/index.dart
            - test/**

      json_serializable|json_serializable:
        generate_for:
          include:
            - lib/**/models/**.dart
            - lib/features/auth/domain/entities/auth_tokens.dart
          exclude:
            - lib/**/index.dart
            - test/**

      riverpod_generator|riverpod_generator:
        enabled: true

global_options:
  freezed:
    options:
      union_value_case: snake
  
  json_serializable:
    options:
      field_rename: none
      explicit_to_json: true
